import Head from "next/head";

import Nav from "../Nav/Nav";
import Footer from "../Footer/Footer";
import styles from "./Layout.module.css";

export default function Layout({ children, title }) {
  return (
    <div className={styles.layout}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Nav />
      </header>
      {children}
      <Footer />
    </div>
  );
}
