import { useContext, useState } from "react";

import Link from "next/link";

import CartContext from "../lib/Cart";
import Layout from "../components/Layout/Layout";
import Head from "next/head";

import styles from "../styles/Cart.module.css";

import { checkOut, CheckOutRedirect } from "../lib/checkout";

function Cart() {
  const { cart, setCart, setTotal, total } = useContext(CartContext);

  const [redirectUrl, setRedirectUrl] = useState("");
  const [isQiwiPay, setQiwiPay] = useState(false);

  const handleClick = async () => {
    const fields = {
      email: "online.easy@yahoo.com",
      cart,
      amount: total,
    };

    const qiwiResponse = await checkOut(fields);
    if (qiwiResponse.payUrl) {

      setRedirectUrl(qiwiResponse.payUrl);
      setQiwiPay(!isQiwiPay);
    }
  };

  return (
    <Layout title="Qiwi Cart">
      <Head>
        <title>Qiwi Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isQiwiPay ? (
        <CheckOutRedirect url={redirectUrl} />
      ) : (
        <section className={styles.cartSummary}>
          <div className={styles["summary-header"]}>
            <Link href="/">
              <a>&#8592; Continue shopping</a>
            </Link>
            <h3>Cart Summary</h3>
            <div className={styles["summary-total-items"]}>
              <button className={styles.checkoutButton} onClick={handleClick}>
                Checkout
              </button>
            </div>
          </div>
          <div className={styles["summary-content-container"]}>
            {cart.map((product, index) => (
              <div className={styles["summary-content"]} key={index}>
                <div className={styles["first-section"]}>
                  <span role="img" aria-label={product.name}>
                    {product.emoji}
                  </span>
                  <h3 className="item-name">{product.name}</h3>
                </div>
                <div className={styles["second-section"]}>
                  <span className={styles["quantity-label"]}>Quantity</span>
                  <div className={styles["update-quantity"]}>
                    <button
                      className={styles["update-button"]}
                      value={product}
                      onClick={() => {
                        setCart({ type: "decrease", product });
                        setTotal(cart);
                      }}
                    >
                      -
                    </button>
                    <div className="quantity">{product.quantity}</div>
                    <button
                      className={styles["update-button"]}
                      value={product}
                      onClick={() => {
                        setCart({ type: "increase", product });
                        setTotal(cart);
                      }}
                    >
                      +
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>
      )}
    </Layout>
  );
}

export default Cart;
